export default {
  lang: "English",
  language: "Language",
  ChangePassword: "Modify Password",
  OldPassword: "Old Password",
  NewPassword: "New Password",
  ConfirmPassword: "Confirm",
  User: "User",
  Logout: "Logout",
  GameCenter: "Game Center",
  ServerManagement: "Server Management",
  GameManagement: "Game Management",
  EventMonitoring: "Event Monitor",
  EventQuery: "Event Query",
  BasicSetting: "Basic Settings",
  LineType: "Network Line",
  BTServer: "BT Server",
  ServerState: "Status",
  BtServerGroup: "BT Server Group",
  BtServerList: "BT Server List",
  BTClient: "BT Client",
  FTPServer: "FTP Server",
  SetRunConfig: "Running Config",
  SeedServerList: "Seeding Server List",
  GameState: "Game Status",
  GameDoseed: "Seeding Logs",
  GameStateDetails: "Game Details",
  ListOfCurrentValidData: "Valid Data List",
  GameDoseedHistory: "Seeding History",
  GameProduceJSOMLog: "Game json File Created Logs",
  GameCompany: "Game Company",
  Gamegroup: "Game Group",
  GameList: "Game List",
  GameStrategy: "Version Policy",
  BtSrvGameStatus: "Game Management",
  BtSrvDistributeGame: "Distribute Game",
  ClusterLoginServer: "Cluster Login Server",
  Save: "Save",
  Creeat: "Create",
  Back: "Back",
  Add: "Add",
  Edit: "Edit",
  Enable: "Enable",
  Disabled: "Disable",
  Get: "Get",
  Data: "Data",
  Success: "Successed",
  Failed: "Failed",
  Search: "Search",
  Not: "Non",
  Server: "Server",
  List: "List",
  Type: "Type",
  Name: "Name",
  PleaseSelectOneItem: "Select",
  Management: "Manage",
  BaseSet: "Basic Settings",
  Line: "Line",
  Seeding: "Seeding",
  Client: "Client PC",
  Set: "Settings",
  Tracker: "Tracker",
  ClusterLogin: "Cluster Login",
  Available: "Enable",
  Operator: "Operator",
  Operation: "Operate",
  LastOperationTime: "Last Time",
  Group: "Group",
  All: "All",
  RunConfig: "Running Config",
  Online: "Online",
  Status: "Status",
  Address: "Address",
  Exceptions: "Exceptions",
  Time: "Time",
  Heartbeat: "Heartbeat",
  Last: "Last",
  Region: "Area",
  Lately: "Recent",
  Message: "Info",
  Offline: "Offline",
  Program: "Program",
  Version: "Version",
  Remarks: "Remarks",
  Initialization: "Initialize",
  Login: "Login",
  Allow: "Enable",
  Anonymous: "Anonymous",
  Global: "Global",
  Max: "Max",
  Connections: "Connections",
  Request: "Request",
  Per: "Single",
  Task: "Tasl",
  Download: "Download",
  Speed: "Speed",
  Upstream: "Up",
  Downstream: "Down",
  Sync: "Synchronize",
  Game: "Game",
  interval: "Tiem Interval",
  Sec: "Sec",
  Reporting: "Report",
  Input: "Input",
  Prohibit: "Disable",
  Runing: "Run",
  Master: "Master",
  Sub: "Slave",
  ExtranetDom: "External Domain Name",
  Source: "Source",
  Machine: "Machine",
  Config: "Config",
  Normal: "Normal",
  Abnormal: "Abnormal",
  Port: "Port",
  Passive: "Passive",
  Upload: "Upload",
  Account: "Account",
  Password: "Password",
  Seed: "Seeds",
  File: "File",
  Path: "Path",
  Cluster: "Cluster",
  Comm: "Communication",
  Pierced: "Penetrate",
  Dispatch: "Scheduling",
  Efficiency: "Efficiency",
  Statistics: "Statistics",
  Detection: "Detection",
  Company: "Company",
  Display: "Display",
  Subtype: "Sub-type",
  General: "General",
  Category: "Category",
  Popular: "Popularity",
  System: "System",
  Tool: "Tool",
  Default: "Defalut",
  Console: "Console",
  Subcategories: "Sub-category",
  Fever: "Hot",
  Center: "Center",
  Params: "Parameter",
  Introduce: "Introduce",
  Menu: "Menu",
  Website: "Website",
  Size: "Size",
  LoadCount: "Load Count",
  SelectType: "Selectable",
  Half: "Half",
  Custom: "Custom",
  Strategy: "Policy",
  StrategyINFO: "The policy has been added",
  DistributeINFO: "Please select a group",
  Distribute: "Distribut",
  Formal: "Offical",
  Bandwidth: "Bandwidth",
  Load: "Load",
  Low: "Low",
  Height: "Height",
  Middle: "Middle",
  Current: "Current",
  Utiliz: "Usage Rate",
  Link: "Connect",
  Latest: "Newest",
  Sample: "Sample",
  Doseed: "Seed",
  Updated: "Updated",
  PercentageUpdated: "Updated Percent",
  ErrorCode: "Error Code",
  Allocated: "Distributed",
  NumberofSyncedCompleted: "Synchronized Count",
  SyncCompletRate: "Synchronized Rate",
  View: "View",
  Done: "Completed",
  StoreRelativePath: "Relative Path",
  FullGameFilename: "Full Name",
  LastUpdated: "Last Updated",
  DoseedServerip: "Seeding Server IP",
  StartDoseedTime: "Start Time",
  UpdateTime: "Update Time",
  IncrementalPacket: "Incremental Packet",
  CompletePacket: "Full Packet",
  StartTime: "Start",
  EndTime: "End",
  Results: "Result",
  Invalid: "Invalid",
  PassWord: "Password",
  Complete: "Completed",
  Incomplete: "Uncompleted",
  Assignee: "Opertator",
  UnSync: "Uncompleted",
  Tfax: "The game company has been existed",
  TGax: "The game category has been existed",
  mecrg: "Password has been modified,please re-login",
  lts: "Login Tips",
  firstletter: "Initial",
  TLax: "The line has been existed",
  Synching: "Synchronizing",
  mmd: "The passwords you typed don't match",
  mmef: "Failed",
  Archive: "Archive",
  TGnax: "The game has been existed",
  DefaultLine: "Default",
  Tgcncbe: "The line name can't be blank",
  Tgnex: "The group has been existed",
  Tgnbe: "The group name can't be blank",
  Ipnb: "Ip can't be blank",
  fne: "The field can't be blank",
  Update: "Update",
  addTracker: "Add Tracker",
  editTracker: "Edit Tracker",
  setRunConfig: "Running Config Setup",
  displayNameE: "The display name has been existed",
  defaultGroup: "Default Group",
  agm: "Add Game Company",
  serverGroup: "Server Group",
  sgf: "Enter game name to search",
  customize: "Custom",
  tip:
    "The default line has been existed!<br/> If you know the operation<br/>Please cancel the default line by manual",
  opttip: "Operation Tips",
  tip2:
    "The default line has been existed!<br/>Need cancel by manual<br/><br/><code>Please proceed with caution��</code>",
  closed: "Close",
  addComment: "Add Remark",
  igm: "Enter game name or ID",
  stopUpload: "Stop Upload",
  deleteGame: "Remove Game",
  Processing: "Poecessing",
  Waitting: "Waitting",
  Delete: "Remove",
  ResourceStatus: "Resource Status"
};
