export default {
  lang:"繁體中文",
  language:"語言",
  ChangePassword:"修改密碼",
  OldPassword: "舊密碼",
  NewPassword:"新密碼",
  ConfirmPassword:"確認密碼",
  User: "用戶",
  Logout: "登出",
  GameCenter:"遊戲中心",
  ServerManagement:"伺服器管理",
  GameManagement:"遊戲管理",
  EventMonitoring:"事件監控",
  EventQuery:"事件查詢",
  BasicSetting:"基礎設置",
  LineType:"線路類型",
  BTServer:"BT 伺服器",
  ServerState:"伺服器狀態",
  BtServerGroup:"BT 伺服器分組",
  BtServerList:"BT 伺服器列表",
  BTClient:"BT 客戶端",
  FTPServer:"FTP 伺服器",
  SetRunConfig:"設置運行時配置",
  SeedServerList:"做種伺服器列表",
  GameState: "遊戲狀態",
  GameDoseed:"遊戲做種事件",
  GameStateDetails: "遊戲狀態詳情",
  ListOfCurrentValidData: "當前有效數據清單",
  GameDoseedHistory: "遊戲做種歷史",
  GameProduceJSOMLog: "遊戲json檔生成日誌",
  GameCompany: "遊戲公司",
  Gamegroup: "遊戲分組",
  GameList: "遊戲列表",
  GameStrategy:"遊戲版本變更策略",
  BtSrvGameStatus: "遊戲管理",
  BtSrvDistributeGame: "分配遊戲",
  ClusterLoginServer:"集群登錄伺服器",
  Save: "保存",
  Creeat: "創建",
  Back: "返回",
  Add: "添加",
  Edit: "編輯",
  Enable: "啟用",
  Disabled: "禁用",
  Get: "獲取",
  Data: "數據",
  Success: "成功",
  Failed: "失敗",
  Search: "搜索",
  Not: "非",
  Server: "伺服器",
  List: "列表",
  Type: "類型",
  Name: "名稱",
  PleaseSelectOneItem: "請選擇一項",
  Management: "管理",
  BaseSet: "基礎設置",
  Line: "線路",
  Seeding: "做種",
  Client: "客戶機",
  Set: "設置",
  Tracker: "Tracker",
  ClusterLogin: "集群登錄",
  Available: "是否啟用",
  Operator: "操作人",
  Operation: "操作",
  LastOperationTime: "最後操作時間",
  Group: "分組",
  All: "全部",
  RunConfig: "運行配置",
  Online: "線上",
  Status: "狀態",
  Address: "地址",
  Exceptions: "異常數",
  Time: "時間",
  Heartbeat: "心跳",
  Last: "最後",
  Region: "區域",
  Lately: "最近",
  Message: "資訊",
  Offline: "離線",
  Program: "程式",
  Version: "版本",
  Remarks: "備註",
  Initialization: "初始化",
  Login: "登錄",
  Allow: "允許",
  Anonymous: "匿名",
  Global: "全局",
  Max: "最大",
  Connections: "連接數",
  Request: "請求",
  Per: "單個",
  Task: "任務",
  Download: "下載",
  Speed: "速度",
  Upstream: "上行",
  Downstream: "下行",
  Sync: "同步",
  Game: "遊戲",
  interval: "時間間隔",
  Sec: "秒",
  Reporting: "上報",
  Input: "輸入",
  Prohibit: "禁止",
  Runing: "運行",
  Master: "主",
  Sub: "從",
  ExtranetDom: "外網功能變數名稱",
  Source: "源",
  Machine: "機器",
  Config: "配置",
  Normal: "正常",
  Abnormal: "異常",
  Port: "端口",
  Passive: "被動",
  Upload: "上傳",
  Account: "帳號",
  Password: "密碼",
  Seed: "種子",
  File: "檔",
  Path: "路徑",
  Cluster: "集群",
  Comm: "通訊",
  Pierced: "穿透",
  Dispatch: "調度",
  Efficiency: "效率",
  Statistics: "統計",
  Detection: "檢測",
  Company: "公司",
  Display: "顯示",
  Subtype: "子類型",
  General: "常規",
  Category: "分類",
  Popular: "熱門",
  System: "系統",
  Tool: "工具",
  Default: "默認",
  Console: "控制臺",
  Subcategories: "子分類",
  Fever: "熱度",
  Center: "中心",
  Params: "參數",
  Introduce: "介紹",
  Menu: "菜單",
  Website: "網站",
  Size: "大小",
  LoadCount: "加載數",
  SelectType: "可選配置",
  Half: "一半",
  Custom: "自定義",
  Strategy: "策略",
  StrategyINFO: "該遊戲策略已經添加",
  DistributeINFO: "必須要選擇一個分組",
  Distribute: "分配",
  Formal: "正式",
  Bandwidth: "帶寬",
  Load: "負載",
  Low: "低",
  Height: "高",
  Middle: "中",
  Current: "當前",
  Utiliz: "使用率",
  Link: "連接",
  Latest: "最新",
  Sample:"採樣",
  Doseed: "做種",
  Updated: "已更新",
  PercentageUpdated: "已更新占比",
  ErrorCode:"錯誤碼",
  Allocated: "已分配",
  NumberofSyncedCompleted: "已同步完成數",
  SyncCompletRate: "同步完成率",
  View: "查看",
  Done: "已完成",
  StoreRelativePath: "存儲相對路徑",
  FullGameFilename: "全遊戲檔案名",
  LastUpdated: "最近更新時間",
  DoseedServerip:"做種伺服器IP",
  StartDoseedTime:"開始做種時間",
  UpdateTime:"更新時間",
  IncrementalPacket:"增量包",
  CompletePacket:"完整包",
  StartTime:"發起時間",
  EndTime:"結束時間",
  Results:"結果",
  Invalid:"無效",
  PassWord: "密碼",
  Complete: "完成",
  Incomplete: "未完成",
  Assignee: "分配人",
  UnSync: "未完成",
  Tfax: "該遊戲公司已存在",
  TGax: "該遊戲分類已存在",
  mecrg: "密碼修改成功，請重新登陸",
  lts: "登錄提示",
  firstletter: "首字母",
  TLax: "該線路已經存在",
  Synching: "同步中",
  mmd: "兩次密碼不一致",
  mmef: "密碼修改失敗"
  Archive: "存檔",
  TGnax: "該遊戲已經存在",
  DefaultLine: "默認線路",
  Tgcncbe: "線路名稱不能為空",
  Tgnex: "該分組名稱已存在",
  Tgnbe: "分組名稱不能為空",
  Ipnb: "Ip地址不能為空",
  fne: "該字段不能為空",
  Update: "更新",
  addTracker: "添加Tracker",
  editTracker: "編輯Tracker",
  setRunConfig: "設置運行配置",
  displayNameE: "該顯示分類顯示名稱已存在",
  defaultGroup: "默認分組",
  agm: "添加遊戲公司",
  serverGroup: "伺服器分組",
  sgf: "輸入需要搜索的遊戲搜索名稱",
  customize: "自定義",
  tip:
    "已存在默認線路，默認線路為唯一。<br/> 如果您知曉您的操作<br/>請手動取消當前默認線路",
  opttip: "操作提示",
  tip2:
    "已存在默認線路<br/>需要手動取消當前默認線路<br/><br/><code>此操作存在風險，請謹慎操作！</code>",
  closed: "關閉",
  addComment: "添加備註",
  igm: "輸入遊戲名稱或遊戲ID",
  stopUpload: "停止上傳",
  deleteGame: "刪除遊戲",
  Processing: "處理中",
  Waitting: "等待中",
  Delete: "刪除",
  ResourceStatus: "資源狀態"

};
